In [2]:
import numpy as np

In [3]:
# Let's make our first numpy array!
x = [1,2,3,4,5]
x = np.array(x)
x

array([1, 2, 3, 4, 5])

In [4]:
# shape tells us the shape of our n-dimensional array
x.shape

(5,)

In [5]:
type(x)

numpy.ndarray

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(matrix)

numpy.ndarray

In [8]:
matrix.shape

(3, 3)

In [10]:
# List index syntax works on numpy arrays!
matrix[0]

array([1, 2, 3])

In [11]:
matrix[0][0]

1

In [13]:
matrix[0,0]

1